#IMPORTS

In [0]:
from skimage import feature
import random
import numpy as np
import cv2
import os
import keras
import seaborn as sns
import pandas as pd



from matplotlib import pyplot as plt
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import sklearn.metrics
from pylab import rcParams

from keras.layers import Dense, Dropout, Flatten, Input, Activation 
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import BatchNormalization
from keras.optimizers import Adam
from keras.models import Sequential
from keras.optimizers import SGD
from sklearn.metrics import classification_report,confusion_matrix

from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from PIL import Image
from PIL.ImageOps import grayscale

In [0]:
dataset = 'https://raw.githubusercontent.com/ezzaimsoufiane/Auto-Insurance-Claims-Fraud-Detection-with-ML/master/insurance_claims.csv'
df = pd.read_csv(dataset)
df.head()

   months_as_customer  age  policy_number  ... auto_year fraud_reported _c39
0                 328   48         521585  ...      2004              Y  NaN
1                 228   42         342868  ...      2007              Y  NaN
2                 134   29         687698  ...      2007              N  NaN
3                 256   41         227811  ...      2014              Y  NaN
4                 228   44         367455  ...      2009              N  NaN

[5 rows x 40 columns]

# Dataset exploration

## Features Identification (Inputs):
 - months_as_customer : How many months did the client spend as a customer of the insuring company
 - age : The age of the Insured.
 - policy_number : Insurance companies use insurance policy number to locate a client's account, it is unique. ID like identificator for the client.
 - policy_bind_date : The policy date is the date written on the policy. The day the insurance company agreed to become the client's insurer.
 - policy_state : The American state which the insured is active.
 -policy_csl 	
 -policy_deductable 	
 -policy_annual_premium 	
 -umbrella_limit 	
 -insured_zip 	
 -insured_sex 	
 -insured_education_level 	
 -insured_occupation 	
 -insured_hobbies 	
 -insured_relationship 	
 -capital-gains 	
 -capital-loss 	
 -incident_date 	
 -incident_type 	
 -collision_type 	
 -incident_severity 	
 -authorities_contacted 	
 -incident_state 	
 -incident_city 	
 -incident_location 	
 -incident_hour_of_the_day 	
 -number_of_vehicles_involved 	
 -property_damage 	
 -bodily_injuries 	witnesses 	
 -police_report_available 	
 -total_claim_amount 	
 -injury_claim 	
 -property_claim 	
 -vehicle_claim 	
 -auto_make 	
 -auto_model 	
 -auto_year

In [0]:
df.shape

(1000, 40)